### ISSUE TITLE
504: GATEWAY_TIMEOUT (VERCEL)

### ISSUE THREAD

**Issue by cgineo** [ArnabXD/bins-su-api#24]
Hey arnab , i've been using this repository more than a year , so this recently happened whenever i put a bin request throught vercel i get a 504: GATEWAY_TIMEOUT (Code: FUNCTION_INVOCATION_TIMEOUT) , what's the solution for this please ? and if the problem is in vercel then is there is an alternative as simple as vercel ? 
Thank you

Screenshot : https://i.ibb.co/BVpjrb4/Screenshot-2022-08-05-at-14-26-24.png

**Comment by ArnabXD** [comment]
I get lots of notifications daily from `GitHub` yet I missed this one. I will look into this issue :)

**Comment by ArnabXD** [comment]
Vercel support has been dropped
