### ISSUE TITLE
Bins.su is back , but there's a problem...

### ISSUE THREAD

**Issue by lovelyguy123** [ArnabXD/bins-su-api#9]
Bins.su is working correctly , but these are the errors when you host this rep on vercel :

22:02:22.561 | Analyzing source code...

22:02:22.573 | Warning: Due to `builds` existing in your configuration file, the Build and Development Settings defined in your Project Settings will not apply. Learn More: https://vercel.link/unused-build-settings

22:02:23.926 | Installing build runtime...

22:02:24.437 | Warning: @now/node@1.8.5: "@now/node" is deprecated and will stop receiving updates on December 31, 2020. Please use "@vercel/node" instead.

22:02:27.518 | Build runtime installed: 3.591s
22:02:30.601 | Looking up build cache...
22:02:30.915 | Build Cache not found

22:02:32.153 | Warning: Due to "engines": { "node": "12.0" } in your `package.json` file, the Node.js Version defined in your Project Settings ("14.x") will not apply. Learn More: http://vercel.link/node-version

22:02:32.158 | Installing dependencies...
22:02:36.644 | > nodemon@2.0.7 postinstall /vercel/path1/node_modules/nodemon
22:02:36.644 | > node bin/postinstall \|\| exit 0

22:02:36.852 | npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@2.3.2 (node_modules/fsevents):
22:02:36.853 | npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.3.2: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})

**Comment by ArnabXD** [comment]
These shouldn't stop the app from running.

> 22:02:32.153 | Warning: Due to "engines": { "node": "12.0" } in your package.json file, the Node.js Version defined in your Project Settings ("14.x") will not apply. Learn More: http://vercel.link/node-version

You can disable the above working by going to App -> Settings -> General -> Node.JS Version. Change it to 12.x and save.

Is the build failing or not , these are warns you can safely ignore now. Although I will reduce them as much as possible

**Comment by lovelyguy123** [comment]
Thanks,

The app is now running without no modifications from last night ( the /api/xxxxxx ) test gave me an error message but now it doesn't i don't know how or why but its working again .

Thanks Arnab :)

**Comment by ArnabXD** [comment]
yes, the errors weren't a serious issue
